"""Initial migration

Revision ID: 2c119e758480
Revises: 
Create Date: 2024-12-18 18:30:21.853904

"""
from alembic import op
import sqlalchemy as sa
from anketa import JsonEncodedList


# revision identifiers, used by Alembic.
revision = '2c119e758480'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Anketa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('elementi', JsonEncodedList(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Korisnik.id'], name=op.f('fk_Anketa_user_id_Korisnik')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Anketa')
    # ### end Alembic commands ###
