"""Add Korisnik model

Revision ID: d1ede83897b5
Revises: 3cf79e30dd85
Create Date: 2024-12-09 19:34:33.195276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1ede83897b5'
down_revision = '3cf79e30dd85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Korisnik',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ime', sa.String(), nullable=False),
    sa.Column('prezime', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('lozinka', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Korisnik')
    # ### end Alembic commands ###
